# Cloudflare Pages build configuration
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.18.0"
  NPM_VERSION = "10"
  
# Force npm instead of bun for compatibility
[build.processing]
  skip_processing = false

# Cache settings
[build.cache]
  # Cache node_modules for faster builds
  paths = ["node_modules", ".npm"]
