name: CI - Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check formatting with Prettier
        run: npm run format

      # - name: Lint code with ESLint
      #   run: npm run lint
      #   # This step is commented out because the ESLint setup is currently broken.
      #   # It should be re-enabled once the configuration is fixed.

      - name: Build project
        run: npm run build
        env:
          # This secret is still needed for the build step to succeed
          PUBLIC_WEB3FORMS_API_KEY: ${{ secrets.PUBLIC_WEB3FORMS_API_KEY }}
